baseURL = "https://konstantinosvoulgaris.com"
languageCode = "en"
title = "Konstantinos Voulgaris"

[params]
    profile = "https://avatars.githubusercontent.com/u/36533602"

    [[params.nav]]
        name = "Blog"
        icon = "fa-solid fa-feather"
        url = "/posts"
        weight = 10
    [[params.nav]]
        name = "Presentations"
        icon = "fa-solid fa-microphone"
        url = "/presentations"
        weight = 20
    [[params.nav]]
        name = "Papers"
        icon = "fa-solid fa-scroll"
        url = "/papers"
        weight = 30
    [[params.nav]]
        name = "CV / Résumé"
        icon = "fa-solid fa-address-card"
        url = "/cv"
        weight = 40

    [[params.external]]
        name = "GitHub"
        icon = "fa-brands fa-github"
        url = "https://github.com/konvoulgaris"
        color = "#000000"
        weight = 10
    [[params.external]]
        name = "LinkedIn"
        icon = "fa-brands fa-linkedin"
        url = "https://linkedin.com/in/konvoulgaris"
        color = "#0A66C2"
        weight = 20
    [[params.external]]
        name = "Google Scholar"
        icon = "fa-solid fa-graduation-cap"
        url = "https://scholar.google.com/citations?user=z3OgBp8AAAAJ&hl=el&oi=sra"
        color = "#DE5246"
        weight = 30
    [[params.external]]
        name = "ResearchGate"
        icon = "fa-brands fa-researchgate"
        url = "https://www.researchgate.net/profile/Konstantinos-Voulgaris-8"
        color = "#00D5AD"
        weight = 40
