baseURL = "https://konstantinosvoulgaris.com"
languageCode = "en"
title = "Konstantinos Voulgaris"


[params]
    startYear = 2022
    profile = "https://avatars.githubusercontent.com/u/36533602"

    [[params.page]]
        name = "Home"
        url = "/"
        weight = 10
    [[params.page]]
        name = "Posts"
        url = "/posts/"
        weight = 20
    [[params.page]]
        name = "Presentations"
        url = "/presentations/"
        weight = 30
    [[params.page]]
        name = "Papers"
        url = "/papers/"
        weight = 40
    [[params.page]]
        name = "CV"
        url = "/cv/"
        weight = 50

    [[params.social]]
        name = "GitHub"
        icon = "fa-brands fa-github"
        url = "https://github.com/konvoulgaris"
        weight = 10
    [[params.social]]
        name = "LinkedIn"
        icon = "fa-brands fa-linkedin"
        url = "https://linkedin.com/in/konvoulgaris"
        weight = 20
    [[params.social]]
        name = "Google Scholar"
        icon = "fa-solid fa-graduation-cap"
        url = "https://scholar.google.com/citations?user=z3OgBp8AAAAJ&hl=el&oi=sra"
        weight = 30
    [[params.social]]
        name = "ResearchGate"
        icon = "fa-brands fa-researchgate"
        url = "https://www.researchgate.net/profile/Konstantinos-Voulgaris-8"
        weight = 40
